CREATE DATABASE IF NOT EXISTS im_admin;CREATE DATABASE IF NOT EXISTS im_friend;
CREATE DATABASE  IF NOT EXISTS im_group;
 CREATE DATABASE  IF NOT EXISTS im_news;
 CREATE DATABASE IF NOT EXISTS im_otc;
 CREATE DATABASE IF NOT EXISTS im_sys;
 CREATE DATABASE IF NOT EXISTS im_wallet;
 CREATE DATABASE IF NOT EXISTS im_web;
  CREATE DATABASE IF NOT EXISTS im_chat;
 CREATE DATABASE IF NOT EXISTS im_user;